name: 'Check Atlantis config'
description: 'Run set of checks on atlantis.yaml config file.'
inputs:
  atlantis-config:
    description: 'Path to "atlantis.yaml" file, relative to $GITHUB_WORKSPACE. Defaults to ./atlantis.yaml'
    required: false
  commit-change:
    description: 'Commit the necessary updates back to PR'
    default: 'false'
    required: false
  sort-by:
    description: 'Sort atlantis projects by the given key ("name" or "dir")'
    default: 'dir'
    required: false
  token:
    description: 'GitHub auth token. For most cases set it to secrets.GITHUB_TOKEN'
    default: ${{ github.token }}
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'
