name: 'Check Atlantis configuration file'
description: 'Run set of checks on "atlantis.yaml" config file.'
inputs:
  atlantis-config:
    description: 'Path to "atlantis.yaml" file, relative to $GITHUB_WORKSPACE. Defaults to ./atlantis.yaml'
    required: false
  commit-change:
    description: 'Commit the necessary updates back to PR'
    default: 'false'
    required: false
  sort-by:
    description: 'Sort atlantis projects by the given key ("name" or "dir")'
    default: 'dir'
    required: false
branding:
  icon: 'check-circle'
  color: 'white'
runs:
  using: 'node16'
  main: 'dist/index.js'
